### PR TITLE
fix(app, secondary): reject if initializeApp fails on iOS

### LINKED ISSUE #5134: App crash on using secondary firebase app on iOS
package.json-
```
    "react": "16.13.1",
    "react-native": "0.63.4",
    "@react-native-firebase/analytics": "11.2.0",
    "@react-native-firebase/app": "11.2.0",
    "@react-native-firebase/auth": "11.2.0",
    "@react-native-firebase/firestore": "11.2.0",
    "@react-native-firebase/messaging": "11.2.0",
    "@react-native-firebase/remote-config": "11.2.0",
```

```
const initGuestChatConnection = async () => { 
  if (firebase.apps.length < 2) {
    await firebase.initializeApp(GUEST_CHAT_FIREBASE_CONFIG, {
      name: GUEST_CHAT_FIREBASE_CONFIG.app_name // 'GUEST_CHAT'
    });
  }
};

const getGuestChatFirebaseInstance = () => {
  return firebase.app(GUEST_CHAT_FIREBASE_CONFIG.app_name);
};

const signInGuestChatFirebaseInstance = token => {
  return getGuestChatFirebaseInstance()
    .auth()
    .signInWithCustomToken(token);
};

const getGuestChatAuthResponse = () => {
  initGuestChatConnection().then(async () => {
    try {
        await signInGuestChatFirebaseInstance('token');
    } catch (error) {
        console.error(error);
    }
 });
};
```

When using auth-

Exception '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil' was thrown while invoking addAuthStateListener on target RNFBAuthModule with params (
    "GUEST_CHAT"
)
image

This is working fine on Android but failing on iOS.

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

Previously the exceptions were swallowed, meaning that initialization failures
were very difficult to diagnose, leading to developer confusion

### Related issues

Fixes #5134

### Release Summary

conventional commit message

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

A great deal of manual testing

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

File: packages/app/lib/internal/registry/app.js [hunk 1]
```diff
@@ -175,6 +177,19 @@ export function initializeApp(options = {}, configOrName) {
...
       app._initialized = true;
       return app;
+    })
+    .catch(e => {
+      // we need to clean the app entry from registry as the app does not actually exist
+      // There are still possible side effects from `onAppCreateFn` to consider but as existing
+      // code may rely on that function running prior to native create, re-ordering it is a semantic change
+      // and will be avoided
+      for (var key in APP_REGISTRY) {
+        if (key == 'bar') {
```
Comment (Salakar) [inline packages/app/lib/internal/registry/app.js:187]: 👀 'bar'?

File: packages/app/ios/RNFBApp/RNFBAppModule.m [hunk 2]
```diff
@@ -205,8 +205,7 @@ - (void)invalidate {
         firApp = [FIRApp appNamed:appName];
       }
     } @catch (NSException *exception) {
-      // TODO js error builder
-      // reject(@"code",@"message",[exception ]);
+      return [RNFBSharedUtils rejectPromiseWithExceptionDict:reject exception:exception];
```
Comment (Salakar) [inline packages/app/ios/RNFBApp/RNFBAppModule.m:208]: 🙈 good spot

File: packages/app/lib/internal/registry/app.js (hunk 1 above)
Comment (mikehardy) [reply packages/app/lib/internal/registry/app.js:187]: Ah crap, obvious copy-paste error, also I realized while on a ride today it had an obvious test I should add to see it fail and then make sure apps length was still 1, which would have of course surfaced this junk immediately. Will correct

File: packages/app/ios/RNFBApp/RNFBAppModule.m (hunk 2 above)
Comment (mikehardy) [reply packages/app/ios/RNFBApp/RNFBAppModule.m:208]: This was the root of a user issue so kudos to them really, I just traced through till I ended up here and was happy it was obvious!

File: packages/app/lib/internal/registry/app.js [hunk 3]
```diff
@@ -175,6 +177,16 @@ export function initializeApp(options = {}, configOrName) {
     .then(() => {
       app._initialized = true;
       return app;
+    })
+    .catch(e => {
+      // we need to clean the app entry from registry as the app does not actually exist
+      // There are still possible side effects from `onAppCreateFn` to consider but as existing
+      // code may rely on that function running prior to native create, re-ordering it is a semantic change
+      // and will be avoided
+      delete APP_REGISTRY[name];
```
Comment (mikehardy) [inline packages/app/lib/internal/registry/app.js:186]: @Salakar it was even worse than your original commit where I committed copy-pasta-cide
I was trying to splice the entry out of object, and of course splice is for arrays.
Anyway, the root cause is one I/we know the answer to: actually test the thing

So now it has an e2e test which was illuminating by itself, because firebase-android-sdk simply doesn't care about bad init values while iOS throws. Who knew? But it's all exercised now with solid assertions :+1:

**Comment by mikehardy** [comment]
I'm comfortable with this one (read as: will obviously fix anything if it comes up) now that I put the test in and exercised it well, going to merge now - thanks for keeping me honest @Salakar

**Comment by Salakar** [comment]
> thanks for keeping me honest @Salakar

boop
