### PR TITLE
fix(app, expo): Update AppDelegate config plugin for Expo SDK 44

### LINKED ISSUE #5936: [🐛] Config Plugin breaks on Expo SDK 44
## Issue

If you upgrade to Expo SDK 44, and run `expo prebuild -p ios --clean`, you get this error:

<details>
<summary>
Click to view error
</summary>

```sh
(Use `node --trace-deprecation ...` to show where the warning was created)
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Failed to match "/(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])/g" in contents:
#import "AppDelegate.h"
@import Firebase;

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [UIColor whiteColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 #endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end

Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])/g" in contents:
#import "AppDelegate.h"
@import Firebase;

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [UIColor whiteColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 #endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end

    at addLines (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/utils/generateCode.ts:82:19)
    at mergeContents (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/utils/generateCode.ts:55:17)
    at modifyObjcAppDelegate (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js:24:45)
    at /Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js:41:28
    at action (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:23)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at action (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
```
</details>

I'm omitting most other fields in this issue, since they don't apply to Expo projects. But let me know if you need any more info.

It was working before upgrading to SDK 44.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^13.1.0",
    "@react-native-firebase/auth": "^13.1.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `13.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `basic installation`
- **Are you using `TypeScript`?**
  - `4.4.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by barthap**
### Description

See https://github.com/invertase/react-native-firebase/issues/5936#issuecomment-994412911

The AppDelegate template for Expo has changed again.
- Updated the existing regex
- _Proposed_ a fallback regex, if the line matched by the previous regex ever changes again (hope not!). It matches for `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:`, but surprisingly is less stable than the previous one. Why? It can be multiline (e.g. the method opening bracket `{` can be in the same or new line). And `mergeContents()` from `@expo/config-plugins` doesn't support multiline matchers. 😒 So I left this solution as a second chance.

## Are we forced to rely on RegExp forever?

> I am leaving it here for further discussion / reference.

Hopefully not. Interestingly, the line that broke SDK 44, actually was part of a change (series of changes), that would allow libraries to define their own _"App Delegate Extensions" (I'm still not sure about the official name)_, which can contain custom code to be executed in `AppDelegate` methods.

In this case, such `extension` could look like this (it's Swift, but afaik there's a possibility to do it in Obj-C too):
```swift
import ExpoModulesCore
import Firebase

public class RNFBExpoAppDelegate: ExpoAppDelegateSubscriber {
  public func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    FirebaseApp.configure()
    return true
  }
}
```
Then, this class name should be provided in one expo-specific configuration file (`expo-module.config.json`) shipped with the library, and expo-modules-autolinking will do the rest.

More info in this PR: https://github.com/expo/expo/pull/14867

This will let us get rid of that regex changes. Why didn't I implement it yet and stay with regex? A couple of reasons:
- It's undocumented yet
- It's introduced in SDK 44, the API might be unstable.
- It most likely requires RNFB to add `ExpoModulesCore` as an iOS pod dependency - I don't want to mess with it here yet. 
- That dependency is a Swift module, but I don't know much about objc-swift interop between libraries

If the above are not blockers, then I can try to implement this.

### Related issues

Fixes #5936

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [x] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

- Regex tested in Regex101 (links in code)
- Tested on an SDK 44 app,
- Updated jest tests and snapshots

### CODE REVIEW

File: packages/app/plugin/src/ios/appDelegate.ts [hunk 1]
```diff
@@ -22,15 +27,44 @@ export function modifyObjcAppDelegate(contents: string): string {
     return contents;
   }
 
+  if (
+    !methodInvocationLineMatcher.test(contents) &&
+    !fallbackInvocationLineMatcher.test(contents)
+  ) {
+    WarningAggregator.addWarningIOS(
+      '@react-native-firebase/app',
+      'The AppDelegate.m may be malfolmed. Skiping adding Firebase to it.',
```
Comment (mikehardy) [inline packages/app/plugin/src/ios/appDelegate.ts:36]:
```suggestion
      'Unable to determine correct Firebase insertion point in AppDelegate.m. Skipping Firebase addition.',
```

Everyone loves to propose changes to user messages, vs working on code ;-)

**Review by mikehardy — DISMISSED** [review]
I have a strong opinion against adding any Pods that are not pointed directly at critical upstream dependencies, e.g. to google firebase pods, so I do not want to pursue that.

I have a second strong opinion that they should base off the raw react-native template so that we are all working from the same base and it would be "stable" since that does not change with much frequency at all. I do a lot of dynamic app construction via script and it works great, I don't know why they are not just sticking to the upstream and "borrowing" it's stability?

This works for me though, with fallback also, that's fine - if you like the comment change, and this gets us going for Expo 44 I'm fine leaving it at that.

I appreciate the continued attention here though - relatively trifling opinions on code aside, I have 10x strong positive opinions of anyone that takes the time to contribute back, thanks @barthap

**Review by mikehardy — APPROVED** [review]
Up to you I think, looks good to me and if you thought it was ready for review (not draft) we could merge as is and release

**Comment by barthap** [comment]
Hah, I marked this as ready moments ago, forgot to click it earlier, sorry 😉

**Comment by nandorojo** [comment]
Is this released btw? Thanks!

**Comment by barthap** [comment]
Yep, 14.0.1

**Comment by mikehardy** [comment]
@nandorojo -> https://invertase.io/blog/react-native-firebase-versioning --> https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md for a happy library user, note those
