### PR TITLE
fix(crashlytics): handle undefined fileName in stack frames

### LINKED ISSUE #3079: TypeError: undefined is not an object (evaluating 'fileName.indexOf') createNativeErrorObj@... 🔥
## Issue

When manually testing an app via `react-native run-android` when I change some source files and therefore a new bundle is created by the Metro bundler and the app is refreshed, I get the warning:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'fileName.indexOf') createNativeErrorObj@...
```

I guess the problem is in `packages/crashlytics/lib/handlers.js` line 31:
```
    const subStrLen = fileName.indexOf('?') < 0 ?
```
here the variable `fileName` is referenced although it could be `undefined`.
I will prepare a PR to fix this bug ...

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Linux 5.3 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 676.00 MB / 15.26 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.2`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by MichaelTamm**
Fixes #3079

### Summary

This PR fixes a potential TypeError in `packages/crashlytics/lib/handlers.js` where
currently the variable `fileName` is dereferenced although it might be `undefined`.

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan

I would have liked to add a test, but did not find a test file for `handlers,js`.

### Release Plan

[ GENERAL  ] [ BUGFIX      ] [ crashlytics ] - Fixed a potential TypeError

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

File: packages/crashlytics/lib/handlers.js [hunk 1]
```diff
@@ -28,17 +28,22 @@ export function createNativeErrorObj(error, stackFrames, isUnhandledRejection) {
...
-    const subStrLen = fileName.indexOf('?') < 0 ? fileName.length : fileName.indexOf('?');
-    const fileNameParsed =
-      fileName && fileName.length ? fileName.substring(0, subStrLen) : '<unknown>';
+    let fileNameParsed = '<unknown>';
+    if (fileName) {
+      const subStrLen = fileName.indexOf('?');
+      if (subStrLen < 0) {
+        fileNameParsed = fileName;
+      } else if (subStrLen > 0) {
+        fileName.substring(0, subStrLen);
```
Comment (mikehardy) [inline packages/crashlytics/lib/handlers.js]: is fileName used after this anywhere? Seems like the result of this is not used because fileNameParsed is what is used below?

Comment (MichaelTamm) [reply packages/crashlytics/lib/handlers.js]: Oh my, you are right, I forgot `fileNameParsed = ` -- just updated the PR.
