### PR TITLE
fix(ios, messaging): register background handler task

### LINKED ISSUE #4104: iOS background handler not always triggered
I've spend more time debugging this than I'm comfortable admitting, but well that's life. 

If you were to search this repo for "ios background" -> you'll find around 30 open issues. Which makes 30% of all open issues. To those of you who think that react-native-firebase doesn't work with ios background notifications - you are wrong. It works! I've been in that boat and I can tell you - it works. Make sure that you compose the right message, with the correct headers. If your app is still not woken up, then use the console.app on your Mac to find out if iOS is blocking the push notifications for some reason. 

Putting those things aside. I could see that our app was being woken up, but the JS backgroundHandler  was not being triggered. Initially I thought that we have a bug in our JS code as the moment I commented some lines out - I could see the handler working. After some time - I noticed that it's not always the same commented out lines that make it work. It was all kind of random. I'll comment a line out - and it would work. Then I'll re-enable this line and it will continue to work... So I thought that we must be having some race condition in our code that provokes this. But after few days I realized that the part that causes this is not in our JS code, but rather on the native side. More precisely here:

```obj-c
      // TODO investigate later - RN bridge gets invalidated at start when in background and a new bridge created - losing all events
      // TODO   so we just delay sending the event for a few seconds as a workaround
      // TODO   most likely Remote Debugging causing bridge to be invalidated
      dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t) (2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [[RNFBRCTEventEmitter shared] sendEventWithName:@"messaging_message_received_background" body:[RNFBMessagingSerializer remoteMessageUserInfoToDict:userInfo]];
      });
```
https://github.com/invertase/react-native-firebase/blob/master/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BAppDelegate.m#L122

In our app the background task actually needs to load the redux store and the redux-saga code. We are talking about a lot of imports. So it turned out that despite setting the listener as one of the first things in index.js we apparently need more than 2s. I increased this to 8s and I can confirm that we are now receiving the message all the time. 

So with this knowledge I think that some of the users who have opened a "ios background data message" issue actually suffer from the above problem. The OS actually delivers the message to the app, but the native code is executed before the bundle is ready and they are left with no message. 

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 247.13 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-24 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 19.0.5232133
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
 "8.3.0",
    
- **`Firebase` module(s) you're using that has the issue:**
  - "@react-native-firebase/messaging": "7.6.1",
- **Are you using `TypeScript`?**
  - N

</p>
</details>

### PR DESCRIPTION
**Pull request by davx1992**
### Description

This PR is needed to fix problem reported in this issue https://github.com/invertase/react-native-firebase/issues/4104 .
https://github.com/invertase/react-native-firebase/issues/4104#issuecomment-683411140

### Related issues

Fixes #4104 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x ] No

### Test Plan
Nothing to add.

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

File: packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m [hunk 1]
```diff
@@ -111,9 +111,22 @@ - (void)application:(UIApplication *)application didReceiveRemoteNotification:(N
     
   if (userInfo[@"gcm.message_id"]) {
     if ([UIApplication sharedApplication].applicationState == UIApplicationStateBackground) {
+      //If app is in background state, register background task
```
Comment (mikehardy) [inline packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m:114]:
```suggestion
      // If app is in background state, register background task to guarantee async queues aren't frozen.
```

File: packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m [hunk 2]
```diff
@@ -111,9 +111,22 @@ - (void)application:(UIApplication *)application didReceiveRemoteNotification:(N
...
+            if (backgroundTaskId != UIBackgroundTaskInvalid) {
+                [application endBackgroundTask:backgroundTaskId];
+                backgroundTaskId = UIBackgroundTaskInvalid;
+            }
+      }];
       // TODO add support in a later version for calling completion handler directly from JS when user JS code complete
       dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t) (25 * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
         completionHandler(UIBackgroundFetchResultNewData);
+
+        //Stoping background task here, as this is longest timeout, so we are sure that it is executed
```
Comment (mikehardy) [inline packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m:125]:
```suggestion
        // Stop background task after the longest timeout, async queue is okay to freeze again after handling period
```

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
Saw this on the issue earlier and it was a 'doh' moment for me, we should have had this in originally but I completely forgot about it when rewriting messaging 🙈 so LGTM.
