### PR TITLE
fix(database): call cancellation callback when using ref.on

### LINKED ISSUE #5370: [🐛] database - cancellationCallback/error callback is not being triggered via ref.on
## Issue

The cancellation/error callback is not being triggered using the following api. This is with @react-native-firebase/database

```
ref.on('value', (val) => ... , (err) => { ... })
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by nealmanaktola**
### Description

The cancellation/error callback is not being triggered using the following api

```
ref.on('value', (val) => ... , (err) => { ... })
```

Digging through the code, I noticed the listener is being wrapped but not called. I noticed there is a test for this...but not sure how that is passing.

### Related issues

Fixes #5370 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X ] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

File: packages/database/lib/DatabaseSyncTree.js [hunk 1]
```diff
@@ -263,7 +263,8 @@ class DatabaseSyncTree {
 
     if (once) {
       const subscription = SharedEventEmitter.addListener(eventRegistrationKey, event => {
-        this._onOnceRemoveRegistration(eventRegistrationKey, listener, event);
+        const wrappedListener = this._onOnceRemoveRegistration(eventRegistrationKey, listener, event);
+        wrappedListener(event);
```
Comment (nealmanaktola) [inline packages/database/lib/DatabaseSyncTree.js:267]: not entirely sure if i am missing something here 😆

**Review by mikehardy — CHANGES_REQUESTED** [review]
As mentioned in comment with details, I don't think this is an error here, and I don't think this is needed. I think there is something else going on, possibly project-specific.

File: packages/database/lib/DatabaseSyncTree.js (hunk 1 above)
Comment (nealmanaktola) [reply packages/database/lib/DatabaseSyncTree.js:271]: @mikehardy that method returns the function...but where is the function called?

Comment (mikehardy) [reply packages/database/lib/DatabaseSyncTree.js:271]: this line *right here* calls it https://github.com/invertase/react-native-firebase/blame/b8f80a41e864c2c8d97602df625abdd2ee6bc347/packages/database/lib/DatabaseSyncTree.js#L323

regarding skipped test, it feels like we are mixing things here. Are we talking about once, or on? You are pointing to _onOnceRemoveRegistration, but you are talking about an 'on' failure. I can't put those together.

Comment (nealmanaktola) [reply packages/database/lib/DatabaseSyncTree.js:271]: Sorry, maybe I am getting confused, but let me try to break this down a bit better.

1. https://github.com/invertase/react-native-firebase/blame/b8f80a41e864c2c8d97602df625abdd2ee6bc347/packages/database/lib/DatabaseSyncTree.js#L323
This line does indeed called the passed listener, but _onOnceRemoveRegistration is returning a function (that calls the passed listener), but that function does not appear to be called

> regarding skipped test, it feels like we are mixing things here. Are we talking about once, or on? You are pointing to _onOnceRemoveRegistration, but you are talking about an 'on' failure.

2. To speak to this a bit better -
Let's take a look at this snippet: 
https://github.com/invertase/react-native-firebase/blob/master/packages/database/lib/DatabaseQuery.js#L313

This is the ref.on method. Notice, it passes `once` as true when registering the cancellation callback. I am assuming `once` is passed as true, because we unsubscribe after triggering the error event / cancel callback


Now if we look at `addRegistration`, 
https://github.com/invertase/react-native-firebase/blame/b8f80a41e864c2c8d97602df625abdd2ee6bc347/packages/database/lib/DatabaseSyncTree.js#L264

It checks to see if `once` is true, and then 
```
      const subscription = SharedEventEmitter.addListener(eventRegistrationKey, event => {
        this._onOnceRemoveRegistration(eventRegistrationKey, listener, event);
        subscription.remove();
      });
```
I hope that clears up 
```
e. Are we talking about once, or on? You are pointing to _onOnceRemoveRegistration, but you are talking about an 'on' failure.
```

Comment (mikehardy) [reply packages/database/lib/DatabaseSyncTree.js:271]: I don't have time to look at this more deeply right now, sorry, I'll queue it for later but I didn't see anything wrong in the code each of the times I've responded and looked again.

**Comment by nealmanaktola** [comment]
@mikehardy Gentle reminder if you had some time to look at this again

I also played around with the tests.

The test that was skipped https://github.com/invertase/react-native-firebase/blob/master/packages/database/e2e/query/on.e2e.js#L111 is failing w/o my patch.

After applying the patch, the test does in fact pass.

**Comment by mikehardy** [comment]
Sorry for the delay, had my mom in town from out of the country for the week 😁, this is in my queue and I do really appreciate the test investigation. We'll get this nailed down

**Comment by photorouletteadmin** [comment]
We faced the same problem. Patched it like this:

```
--- a/node_modules/@react-native-firebase/database/lib/DatabaseSyncTree.js
+++ b/node_modules/@react-native-firebase/database/lib/DatabaseSyncTree.js
@@ -263,7 +263,7 @@ class DatabaseSyncTree {
 
     if (once) {
       const subscription = SharedEventEmitter.addListener(eventRegistrationKey, event => {
-        this._onOnceRemoveRegistration(eventRegistrationKey, listener, event);
+        this._onOnceRemoveRegistration(eventRegistrationKey, listener)(event);
         subscription.remove();
       });
     } else {
```

I think this error was introduced by this commit: https://github.com/invertase/react-native-firebase/commit/5eb2f599e93ccecd91c800018959f9dc370f1e24. Looks like some of the other callbacks are also not being called.

**Comment by mikehardy** [comment]
Believe it or not (and you may not as this has sat a while) this is a high priority to fix for me and I'm sorry (for @nealmanaktola ) that I haven't reviewed it and gotten it worked into a release yet - had quite a few things going on unfortunately.

This *will* be resolved though, hopefully sooner than later

File: packages/database/lib/DatabaseSyncTree.js [hunk 2]
```diff
@@ -263,7 +263,12 @@ class DatabaseSyncTree {
 
     if (once) {
       const subscription = SharedEventEmitter.addListener(eventRegistrationKey, event => {
-        this._onOnceRemoveRegistration(eventRegistrationKey, listener, event);
+        const wrappedListener = this._onOnceRemoveRegistration(
+          eventRegistrationKey,
+          listener,
+          event,
+        );
+        wrappedListener(event);
```
Comment (mikehardy) [inline packages/database/lib/DatabaseSyncTree.js:271]:
```suggestion
        this._onOnceRemoveRegistration(eventRegistrationKey, listener)(event);
```

**Review by mikehardy — APPROVED** [review]
@nealmanaktola thanks again for making this PR, and thanks @photorouletteadmin - I think your one-liner is also correct but easier to read so I've updated the PR with it.
Pending CI this looks good to go and I'll do a release once it's green
@photorouletteadmin you mentioned you thought other callbacks weren't being called, I scanned the rest of the commit that created this issue (it was mine! sorry) and it seems like this was the only one affected but I'd be happy to merge anything else if you find something

**Comment by mikehardy** [comment]
Good to go!
