### PR TITLE
fix(auth): user.metadata uses ISO strings

### LINKED ISSUE #2555: [v6][auth] UserMetadata times are milliseconds, should be ISO Date
@ehesp @Salakar

### PR DESCRIPTION
**Pull request by russellwheatley**
fixes #2555

### CODE REVIEW

File: packages/auth/lib/User.js [hunk 1]
```diff
@@ -19,6 +19,21 @@ import { isObject, isString } from '@react-native-firebase/app/lib/common';
 
 export default class User {
   constructor(auth, user) {
+    if (user) {
+      const { metadata } = user;
+
+      if (metadata && metadata.creationTime && metadata.lastSignInTime) {
```
Comment (Ehesp) [inline packages/auth/lib/User.js]: I think this logic would be better placed in the getter?

File: packages/auth/e2e/user.e2e.js [hunk 2]
```diff
@@ -396,4 +396,20 @@ describe('auth().currentUser', () => {
...
+    it("should have the properties 'lastSignInTime' & 'creationTime' which are ISO strings", async () => {
+      const random = Utils.randString(12, '#aA');
+      const email = `${random}@${random}.com`;
+
+      const { user } = await firebase.auth().createUserWithEmailAndPassword(email, random);
+
+      const { metadata } = user;
+
+      should(metadata.lastSignInTime).be.a.String();
+      should(metadata.creationTime).be.a.String();
```
Comment (Salakar) [inline packages/auth/e2e/user.e2e.js]: Could we do an additional check here to make sure the date is valid, e.g. new date the ISO date string and check the year is the same as the current dates year - this check ensure then that the number that comes from native also valid (seconds vs milliseconds)

```js
(new Date(metadata.lastSignInTime)).getFullYear().should.equal((new Date()).getFullYear());
(new Date(metadata. creationTime)).getFullYear().should.equal((new Date()).getFullYear());
```
