### PR TITLE
fix(auth): Make REVERSED_CLIENT_ID optional

### LINKED ISSUE #8462: [🐛] 🔥 Firebase Auth module requires REVERSE_CLIENT_ID for iOS even when only using email authentication
## Issue

The @react-native-firebase/auth module is requiring a REVERSE_CLIENT_ID field in the GoogleService-Info.plist file during iOS prebuild, even though I'm only using email/password authentication and not Google Sign-In.

When running npx expo prebuild --platform ios, I get this error:

```
✖ Prebuild failed
Error: [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Failed to parse your GoogleService-Info.plist. Are you sure it is a valid Info.Plist file with a REVERSE_CLIENT_ID field?
```

This is forcing me to enable Google Sign-In in Firebase (which I don't need or want to use) just to get the REVERSE_CLIENT_ID field in my configuration file.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "dependencies": {
    "@react-native-firebase/app": "^x.x.x",
    "@react-native-firebase/auth": "^x.x.x",
    "expo": "^x.x.x",
    "react-native": "x.x.x"
  }
}

```

Authentication code only uses email/password auth
```
const handleSignup = () => {
    auth()
      .createUserWithEmailAndPassword(email, password)
      .then(() => {
        // Signed in
        Alert.alert("Success", "Account created successfully!");
        navigation.navigate("Login");
      })
      .catch(error => {
        if (error.code === "auth/email-already-in-use") {
          Alert.alert("Error", "That email address is already in use!");
        } else if (error.code === "auth/invalid-email") {
          Alert.alert("Error", "That email address is invalid!");
        } else {
          Alert.alert("Error", error.message);
        }
      });
  };
```

The REVERSE_CLIENT_ID field is missing from my GoogleService-Info.plist file. Firebase did not generate one for me because I'm not using Google Sign-In, but the module needs it anyway.

### Environment
# Platform that you're experiencing the issue on:

iOS

### react-native-firebase version you're using that has this issue:

Latest version

### Firebase module(s) you're using that has the issue:

@react-native-firebase/auth

### Are you using TypeScript?

No

### Expected Behavior
The @react-native-firebase/auth module should only validate for configuration fields that are necessary for the authentication methods I'm actually using. Since I'm only using email/password authentication and not Google Sign-In, it shouldn't require the REVERSE_CLIENT_ID field to be present in my GoogleService-Info.plist file.

### Actual Behavior
The module is requiring the REVERSE_CLIENT_ID field to be present during prebuild, even though I'm not using Google Sign-In. This forces me to enable Google Sign-In in Firebase (which I don't need) just to get the REVERSE_CLIENT_ID field in my configuration file.

### Workarounds
The only workaround I've found is to enable Google Sign-In in Firebase, download a new GoogleService-Info.plist file that includes the REVERSE_CLIENT_ID field, and then use that for building - even though I don't actually use Google Sign-In in my app.

### PR DESCRIPTION
**Pull request by MichaelVerdon**
### Description

- Fixes #8462

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
  - [ ] `Other` (macOS, web)
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

File: packages/auth/plugin/src/ios/urlTypes.ts [hunk 1]
```diff
@@ -84,8 +91,10 @@ export function setUrlTypesForCaptcha({
     );
   }
 
-  const reversedClientId = getReversedClientId(googleServiceFilePath);
-  addUriScheme(config, reversedClientId);
+  if(reversedClientIDExists(googleServiceFilePath)) {
+    const reversedClientId = getReversedClientId(googleServiceFilePath);
+    addUriScheme(config, reversedClientId);
+  }
```
Comment (mikehardy) [inline packages/auth/plugin/src/ios/urlTypes.ts:97]: may be worth putting an else branch in here with a console.warn saying something like `reversed client id field not found in GoogleServices-Info.plist. Google Sign-In requires this is - if you need Google Sign-In, enable it and re-download your plist file`

Or something like that - it is kind of wordy but I'd rather have an extra console.log during build then a bunch of subtle issues in the github issue tracker later from Expo people that are lost, and we've forgotten why it was even needed ourselves...

**Review by mikehardy — CHANGES_REQUESTED** [review]
Pretty good - I like this - one comment to leave a breadcrumb for devs maybe, and it looks like it needs a javascript/typescript format for lint?

**Review by mikehardy — APPROVED** [review]
I like it - I will admit that's a verbose warning but I couldn't think how to make it shorter and now devs will know what+why 🤷  - so looks good to me, thanks @MichaelVerdon

**Comment by mgray88** [comment]
Thank you for this @MichaelVerdon! Will this be released soon @mikehardy?

**Comment by mikehardy** [comment]
Yep - we have some tiny but still breaking changes (easy to handle, don't worry) that I'm waiting for a go/no-go on. Then I'll do a release later today that will have this either way. Cheers

**Comment by mikehardy** [comment]
@mgray88 released now, as mentioned it was packaged with breaking changes but also as mentioned nothing to fear - the CHANGELOG for v22 has explicit information on how to handle the (in my opinion) small breaking changes. https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md

Cheers
