### PR TITLE
fix(messaging): initialize app props method to fix isHeadless property 

### LINKED ISSUE #3983: isHeadless property not being populated while iOS is quit
## Issue

Hello,

I got stacked with an issue when isHeadless property is not injected while iOS is in the quit state and data message triggers the iPhone to wake up.

This leads to the following: 
1. When I receive a message, my app is fully launched in the background
2. It doesn't proceed with some of the API requests when the user actually opens the app

Any help will be much appreciated

Here is my index.js:

```
import React from 'react'
import { AppRegistry } from 'react-native'
import App from './src/App'
import { name as appName } from './app.json'
import messaging from '@react-native-firebase/messaging'
import { processBackgroundNotification } from 'utils/notifications'

messaging().setBackgroundMessageHandler(async (remoteMessage) => {
  processBackgroundNotification(remoteMessage)
  return Promise.resolve({})
})

function HeadlessCheck({ isHeadless }) {

// ======> isHeadless is always null if data message is received in the quit state

  if (isHeadless) {
    return null
  }
  return <App />
}

AppRegistry.registerComponent(appName, () => HeadlessCheck)
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@dudigital/react-native-zoomable-view": "^1.0.15",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.3.0",
    "@react-native-community/viewpager": "^4.0.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/messaging": "^7.4.2",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "axios": "0.19.2",
    "i18n-js": "^3.7.1",
    "lodash": "^4.17.15",
    "moment": "^2.27.0",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-device-info": "^5.6.1",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-localize": "^1.4.0",
    "react-native-push-notification": "^4.0.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-share": "^3.7.0",
    "react-native-size-matters": "^0.3.0",
    "react-native-svg": "^12.1.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0"
  },
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>
---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 183.13 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `8.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `messaging`
- **Are you using `TypeScript`?**
  - `Y, 3.8.3`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by russellwheatley**
WIP - I have not been able to test properly (outside of preliminary tests) because the FCM gods are not with me today, and my messages are being blocked to my device when my app is in a quit state. Will try again soon unless someone else has it all set up and would like to confirm.

### Description

- Created a `initializeAppProps` helper method. This ought to guarantee the `isHeadless` property is present in the properties passed to the component registered. i.e. `registerComponent` component. This is used when the app is in a quit state and receives a message via FCM for iOS. The `setBackgroundMessageHandler` is called and the app is also silently booted, this prop will allow the developer to return `null` based on `isHeadless === true`.

- The bug is a result of the application booting before the `isHeadless` property is added to the `appProperties` for the `RCTRootView` instance.

### Related issues

fixes #3983

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [X] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

File: packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.h [hunk 1]
```diff
@@ -20,5 +20,5 @@
 
 
 @interface RNFBMessagingModule : NSObject <RCTBridgeModule>
-
++ (NSMutableDictionary *) initializeAppProps: (NSDictionary *)existingProps launchOptions: (NSDictionary *) launchOptions;
```
Comment (Salakar) [inline packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.h:23]:
```suggestion
+ (NSDictionary *_Nonnull) addCustomPropsToUserProps:(NSDictionary *_Nullable)userProps withLaunchOptions:(NSDictionary *_Nonnull)launchOptions;
```

Can we change it to something like this?

**Comment by mikehardy** [comment]
false negative on E2E in iOS this time (android ran clean!), I restarted it, will look at iOS next

File: packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.h [hunk 2]
```diff
@@ -20,5 +20,5 @@
 
 
 @interface RNFBMessagingModule : NSObject <RCTBridgeModule>
-
++ (NSMutableDictionary *) addCustomPropsToUserProps: (NSDictionary *__nullable)userProps withLaunchOptions: (NSDictionary *__nullable) launchOptions;
```
Comment (Salakar) [inline packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.h:23]:
```suggestion
+ (NSDictionary *) addCustomPropsToUserProps: (NSDictionary *__nullable)userProps withLaunchOptions: (NSDictionary *__nullable) launchOptions;
```

Doesn't need to be a mutable dict since internally we call `mutableCopy`.
