### PR TITLE
fix: update Expo plugin to be compatible with objcpp

### LINKED ISSUE #6221: [🐛] Expo SDK 45 error - Can't compile AppDelegate.mm
## Issue

We have an app using SDK 44 and our set up worked just fine. We are building the app using EAS. This morning we tried to upgrade to Expo SDK 45 and React Native 0.68 and while building we had this error in fastlane:

CleanShot_2022-04-28_at_07 55 012x

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"@react-native-firebase/app": "^14.9.0",
"@react-native-firebase/dynamic-links": "^14.9.0",
"@react-native-firebase/messaging": "^14.9.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
I don't have a firebase.json file
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods per say as I use EAS to compile our app.

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
I don't have access to this file
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] We are mostly focus on iOS
- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both - We are using EAS to build the app and this is where it crashes.
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - Yes & version 4.3.5

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by kbrandwijk**
### Description

Expo SDK 45, which is now in beta, has switched to using `objcpp` for `AppDelegate` on iOS. The current import syntax, using `@import`, is incompatible with this. Therefore, SDK 45 beta users using the config plugin are experiencing build issues. This change is backwards compatible with `cpp`, Firebase switched to it 2 years ago (https://github.com/firebase/FirebaseUI-iOS/issues/875 and the linked PR in that issue).

### Related issues

Fixes #6221 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [X] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by kbrandwijk** [comment]
I'm getting an empty page when opening the CLA... 
image

File: packages/app/plugin/src/ios/appDelegate.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export function modifyObjcAppDelegate(contents: string): string {
     contents = contents.replace(
       /#import "AppDelegate.h"/g,
       `#import "AppDelegate.h"
-@import Firebase;`,
+#import <Firebase/Firebase.h>`,
```
Comment (barthap) [inline packages/app/plugin/src/ios/appDelegate.ts:22]: According to [the RNFB docs](https://rnfirebase.io/#configure-firebase-with-ios-credentials), I don't know if it shouldn't be `#import <Firebase.h>` 🤔

**Review by barthap — APPROVED** [review]
Looks good, thanks 😁 I missed that change in my PR.

**Comment by barthap** [comment]
Fixes #6221

File: packages/app/plugin/src/ios/appDelegate.ts (hunk 1 above)
Comment (mikehardy) [reply packages/app/plugin/src/ios/appDelegate.ts:22]: I believe we use to advice using `@import Firebase` a long time ago, but we also switched, maybe that's the confusion?

Either way this reminded me of some previous issues, and in triage of those we made sure both ways work (or, worked - `@import` won't work now I understand that:
https://github.com/invertase/react-native-firebase/pull/4069

Also, I made this change myself recently in my demo script - which hadn't been updated from `@import` style yet, and I can say I know this is working as well with new style:
https://github.com/mikehardy/rnfbdemo/commit/cfed4d8f30eedb196410f3148a0d72257dcb1351#diff-3e27ae623577d0c559bd8ab973a0c34af8cc65ef9beb9868a9cdb029854f8078R33

Which is all to say: I'm pretty comfortable this will be backwards compatible (excellent!) and also I know for RN68 you need it as well

**Review by mikehardy — APPROVED** [review]
This looks great! And yes, I discovered it was needed as well, when I updated my demo script to the RN68 builds, but didn't think of the expo plugins here :-). Thanks for posting this, and sorry about the CLA-bot hassle - who knows what happened there
I'll push a patch release in a moment

**Comment by mikehardy** [comment]
I'm short-cutting some of the CI steps because I just ran through everything and did a release yesterday, plus I know which aspects could/would change based on these file edits. So I've merged it after seeing the affected jobs complete and likewise I know what's affected on main (nothing, vs this PR) so I just kicked off the publish workflow. Should have a patch version up on npmjs.com in a few minutes. Cheers!
