### PR TITLE
fix(auth, ios): factorId nil check

### LINKED ISSUE #7080: [🐛] [iOS] [Auth] - The app crash on iOS when I login.
## Issue

The app build successful but once I login I get this error. It was working fine until yesterday so I guess it's something related to the new update. For sure it's something in the AuthModule since if I disable the MFA it works fine.

```
2023-04-27 10:31:45.333976+0200 MyApp[82893:36653136] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[3]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001804bd1c8 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00000001804c8f4c -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
	4   CoreFoundation                      0x00000001804a7178 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 252
	5   CoreFoundation                      0x0000000180436070 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 48
	6   MyApp                       0x0000000104bba1e4 -[RNFBAuthModule convertMultiFactorData:] + 764
	7   MyApp                       0x0000000104bb9b7c -[RNFBAuthModule firebaseUserToDict:] + 2560
	8   MyApp                       0x0000000104bb8ffc -[RNFBAuthModule constantsToExport] + 604
	9   MyApp                       0x0000000104dba840 __57-[RCTModuleData gatherConstantsAndSignalJSRequireEnding:]_block_invoke + 44
	10  MyApp                       0x0000000104e21aa8 RCTUnsafeExecuteOnMainQueueSync + 52
	11  MyApp                       0x0000000104dba5fc -[RCTModuleData gatherConstantsAndSignalJSRequireEnding:] + 696
	12  MyApp                       0x0000000104dba338 -[RCTModuleData gatherConstants] + 40
	13  MyApp                       0x0000000104d68c34 __49-[RCTCxxBridge _prepareModulesWithDispatchGroup:]_block_invoke + 192
	14  libdispatch.dylib                   0x000000010c18c528 _dispatch_call_block_and_release + 24
	15  libdispatch.dylib                   0x000000010c18dd50 _dispatch_client_callout + 16
	16  libdispatch.dylib                   0x000000010c19e978 _dispatch_main_queue_drain + 1684
	17  libdispatch.dylib                   0x000000010c19e2d4 _dispatch_main_queue_callback_4CF + 40
	18  CoreFoundation                      0x000000018039a784 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
	19  CoreFoundation                      0x0000000180394de4 __CFRunLoopRun + 1912
	20  CoreFoundation                      0x0000000180394254 CFRunLoopRunSpecific + 584
	21  GraphicsServices                    0x0000000188eb7c9c GSEventRunModal + 160
	22  UIKitCore                           0x000000011ffdeff0 -[UIApplication _run] + 868
	23  UIKitCore                           0x000000011ffe2f3c UIApplicationMain + 124
	24  MyApp                       0x0000000104394bc4 main + 300
	25  dyld                                0x000000010bab5514 start_sim + 20
	26  ???                                 0x000000010bbb1e50 0x0 + 4491779664
	27  ???                                 0x1148000000000000 0x0 + 1245245296967942144
)
libc++abi: terminating due to uncaught exception of type NSException
```

#### `package.json`:

```
    ...
    @react-native-firebase/app": "^16.4.6",
    "@react-native-firebase/auth": "^16.4.6",
    "@react-native-firebase/database": "^16.4.6",
    "@react-native-firebase/firestore": "^16.4.6",
    "@react-native-firebase/functions": "^16.4.6",
    "@react-native-firebase/messaging": "^16.4.6",
    "@react-native-firebase/storage": "^16.4.6"
    ...
    "react-native": "0.70.6"
```

## Environment

  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
  -  Latest RN Version cause I've just reinstall it and it stopped working since yesterday

### PR DESCRIPTION
**Pull request by vargajacint**
### Description

Sometimes the `hint.factorID` (in the `firebaseUserToDict` function) is retuning `nil` value and this could cause app crash. I've tried to described my journey with this issue in [this comment](https://github.com/invertase/react-native-firebase/issues/7080#issuecomment-1870635173)

### Related issues
Fixes #7080 

### Release Summary

Auth module - nil check in the getJSFactorId function

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

🔥

### CODE REVIEW

File: packages/auth/ios/RNFBAuth/RNFBAuthModule.m [hunk 1]
```diff
@@ -1374,11 +1374,11 @@ - (NSDictionary *)multiFactorResolverToDict:(FIRMultiFactorResolver *)resolver {
 }
 
 - (NSString *)getJSFactorId:(NSString *)factorId {
-  if ([factorId isEqualToString:@"1"]) {
+  if (factorId == nil || [factorId isEqualToString:@"1"]) {
     // Only phone is supported by the front-end so far
     return @"phone";
   }
-
+
```
Comment (mikehardy) [inline packages/auth/ios/RNFBAuth/RNFBAuthModule.m:1381]: This is a really minor point, but please don't mix spacing changes into functional changes as it makes the diff unnecessarily larger. Additionally our formatting is all automated (via `yarn lint:ios:fix` if I remember correctly, and checked via `yarn lint:ios:check` again if I remember correctly - so this will likely cause a CI failure

Spacing changes just generally best avoided...

```suggestion

```

File: packages/auth/ios/RNFBAuth/RNFBAuthModule.m [hunk 2]
```diff
@@ -1649,7 +1649,7 @@ - (NSDictionary *)firebaseUserToDict:(FIRUser *)user {
         [[[NSISO8601DateFormatter alloc] init] stringFromDate:hint.enrollmentDate];
     [enrolledFactors addObject:@{
       @"uid" : hint.UID,
-      @"factorId" : [self getJSFactorId:(hint.factorID)],
+      @"factorId" : [self getJSFactorId:(hint.factorID == nil ? nil : hint.factorID)],
```
Comment (mikehardy) [inline packages/auth/ios/RNFBAuth/RNFBAuthModule.m:1652]: This is an interesting choice 🤔 - here you check for nil before even calling the method, and if it is nil you ...pass a fresh nil in ?

Then in the method you always return `phone` if it is nil? It seems this check here is likely not needed / redundant, and the nil check in the method itself is likely sufficient?

At the same time, if it is nil, is returning "phone" really correct? Seems like handling it similar to `hint.displayName` below and doing this might be more accurate?

```suggestion
      @"factorId" : hint.factorID == nil ? [NSNull null] : [self getJSFactorID:(hint.factorID),
```

File: packages/auth/ios/RNFBAuth/RNFBAuthModule.m [hunk 3]
```diff
@@ -1374,11 +1374,11 @@ - (NSDictionary *)multiFactorResolverToDict:(FIRMultiFactorResolver *)resolver {
 }
 
 - (NSString *)getJSFactorId:(NSString *)factorId {
-  if ([factorId isEqualToString:@"1"]) {
+  if (factorId == nil || [factorId isEqualToString:@"1"]) {
```
Comment (mikehardy) [inline packages/auth/ios/RNFBAuth/RNFBAuthModule.m:1377]: If as I propose below we guard against nil ever coming in here then this change should be unnecessary.
I'm also not sure converting a "nil" into a return value that semantically means "phone is enrolled" is correct so this change is doubtful for me from a correctness perspective

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hey - thanks a bunch for working through this. I'm sorry it is crashing for you and I'm certain we need a change here so I really appreciate the investigation

I've let some comments on the specific direction for the change and I'm curious for your thoughts on the comments - after a little conversation between us I'm sure we'll come up with something that we agree on and we can get a fix released for this

**Comment by vargajacint** [comment]
Hey @mikehardy,
Yeah you were right, I've applied your suggested changes! Thank you, and happy new year!

**Review by mikehardy — APPROVED** [review]
This looks clean and easy to me - I'm a +1 on it - does it work for you to solve the crash in testing?

**Comment by mikehardy** [comment]
Already passed iOS, android code didn't change --> good to go
