### PR TITLE
fix(messaging): Missing notification on restart

### LINKED ISSUE #5167: 🔥 Notification Object Missing in getInitialNotification() After Restart (Android)
## Issue

The issue is similar (or perhaps the same) as described here: https://github.com/invertase/react-native-firebase/pull/4634

However, there was either a regression, or it wasn't fully fixed.

Notification object is missing if you do this:

1. Kill the app (this may not be necessary, but the app at least has to be in the background)
2. Send a notification to the app, but don't open it.
3. Start the app normally.
4. Kill the app.
5. Click on the notification to start the app

The notification object will be missing in getInitialNotification()

In a normal/correct case you get this:

```
{"notification":{"android":{},"body":"test2","title":"test"},"sentTime":1618360914831,"data":{},"from":"557990742577","messageId":"0:1618360914836382%26d15a5d26d15a5d","ttl":2419200,"collapseKey":"com.repromessagingbug"}
```

In the broken case described above, you get:
```
{"sentTime":0,"collapseKey":"com.repromessagingbug","ttl":2419200,"to":"0:1618361154602496%26d15a5d26d15a5d","data":{},"messageId":"0:1618361154602496%26d15a5d26d15a5d"}
```

---

## Project Files

I put together a minimal reproduction here: https://github.com/mcorner/ReproMessagingBug/

Though it is just a stock RN app with enough code to get the FCM token and print the results of getInitialNotification()

### Javascript

<details><summary>Click To Expand</summary>
<p>

https://github.com/mcorner/ReproMessagingBug/blob/master/App.js

#### `package.json`:

https://github.com/mcorner/ReproMessagingBug/blob/master/package.json

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

N/A, Android issue.

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

N/A, Android issue.

#### `AppDelegate.m`:

N/A, Android issue.

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

https://github.com/mcorner/ReproMessagingBug/blob/master/android/app/build.gradle

#### `android/settings.gradle`:

https://github.com/mcorner/ReproMessagingBug/blob/master/android/settings.gradle

#### `MainApplication.java`:

https://github.com/mcorner/ReproMessagingBug/blob/master/android/app/src/main/java/com/repromessagingbug/MainApplication.java

#### `AndroidManifest.xml`:

https://github.com/mcorner/ReproMessagingBug/blob/master/android/app/src/main/AndroidManifest.xml

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 192.00 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 11.2.0
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - N

</p>
</details>

### PR DESCRIPTION
**Pull request by mcorner**
### Description

When deserializing saved notifications from the store on Android, this pull will include the notification object as well.  Previously the code used the Firebase RemoteMessage class, but that does not allow setting the notification object.  This uses writablemaps instead.

This is an Android only issue.

### Related issues

Fixes #5167

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

After following the reproduction steps in the linked issue, I can now get the notification object on start:

LOG  {"ttl":2419200,"from":"557990742577","to":"0:1618554006404925%26d15a5d26d15a5d","data":{},"sentTime":2147483647,"messageId":"0:1618554006404925%26d15a5d26d15a5d","collapseKey":"com.repromessagingbug","notification":{"android":{},"title":"test","body":"test"}}

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mcorner** [comment]
@mikehardy One development question...  What is the easiest way to link to this pull/commit in another project to use/test it?  Normally in "simpler" packages I can just link to the branch in github directly in a package.json, but that doesn't work here (no version and seemingly other complexities).  I couldn't get yarn link to work properly either with the packages structure.  

I would like to use this in our product in advance of the pull getting approved and published.  

Thanks!

**Comment by mikehardy** [comment]
Hi there! Thanks for the PR - I'll look through it as soon as I get a chance - but to your specific question, I noticed this was a problem for collaboration (both in development and testing) among the community here so I implemented an automated patch-package patch creator :-) #4182

- find the ["Details" link](https://github.com/invertase/react-native-firebase/pull/5181/checks?check_run_id=2359700301) for the "Create Test Patches" GitHub Action run
- look for the "Artifacts" dropdown near-ish to top, sort of on right side and grab the [`patches.zip` file](https://github.com/invertase/react-native-firebase/suites/2509774048/artifacts/54276082)
- install [patch-package](https://github.com/ds300/patch-package) if you have not already (it's fantastic)
- drop the patches in and `yarn install`
- test the feature, integrated in your own app(s), until it's released

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java [hunk 1]
```diff
@@ -2,8 +2,8 @@
 
 import com.facebook.react.bridge.Arguments;
 import com.facebook.react.bridge.ReadableMap;
-import com.facebook.react.bridge.ReadableMapKeySetIterator;
 import com.facebook.react.bridge.WritableMap;
+import com.facebook.react.bridge.ReadableMapKeySetIterator;
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java:6]: Moving the import appears irrelevant to the PR? And it has the effect of un-sorting them - this change should be reverted

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java [hunk 2]
```diff
@@ -2,10 +2,12 @@
 
 import com.google.firebase.messaging.RemoteMessage;
 
+import com.facebook.react.bridge.WritableMap;
+
 public interface ReactNativeFirebaseMessagingStore {
   void storeFirebaseMessage(RemoteMessage remoteMessage);
 
-  RemoteMessage getFirebaseMessage(String remoteMessageId);
+  WritableMap getFirebaseMessage(String remoteMessageId);
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java:10]: This is a breaking change if done like this - is it possible to maintain the original symbol, mark it as deprecated, and make new symbol `getFirebaseMessageMap`?

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java [hunk 3]
```diff
@@ -48,15 +48,15 @@ public void storeFirebaseMessage(RemoteMessage remoteMessage) {
   }
 
   @Override
-  public RemoteMessage getFirebaseMessage(String remoteMessageId) {
+  public WritableMap getFirebaseMessage(String remoteMessageId) {
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java:51]: deprecated original symbol implementation could then call new implementation (that does the map) and just pass it through `remoteMessageFromReadableMap` as it does now.

Not the most important thing in the world but avoiding breaking changes + sticking to semver is such a huge win for library consumers that it is still important

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java [hunk 4]
```diff
@@ -77,9 +78,10 @@ public void getInitialNotification(Promise promise) {
           if (messageId != null && initialNotificationMap.get(messageId) == null) {
             RemoteMessage remoteMessage = ReactNativeFirebaseMessagingReceiver.notifications.get(messageId);
             if (remoteMessage == null) {
-              remoteMessage = popRemoteMessageFromMessagingStore(messageId);
-            }
-            if (remoteMessage != null) {
+              promise.resolve(popRemoteMessageMapFromMessagingStore(messageId));
+              initialNotificationMap.put(messageId, true);
+              return;
+            } else {
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:84]: Hmm - I actually find this harder than it needs to be as a diff, and now there is duplicated logic.

It seems like the only change you *really* need to make is to change `popRemoteMessageFromMessagingStore` to be `popRemoteMessageMapFromMessagingStore` - can this entire diff block be reduced to that one change?

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java [hunk 5]
```diff
@@ -216,18 +218,19 @@ public void onNewIntent(Intent intent) {
...
+          initialNotification = remoteMessageMap;
+          emitter.sendEvent(ReactNativeFirebaseMessagingSerializer.remoteMessageMapToEvent(remoteMessageMap, true));
+        } else {
+          initialNotification = ReactNativeFirebaseMessagingSerializer.remoteMessageToWritableMap(remoteMessage);
           ReactNativeFirebaseMessagingReceiver.notifications.remove(messageId);
-
-          ReactNativeFirebaseEventEmitter emitter = ReactNativeFirebaseEventEmitter.getSharedInstance();
           emitter.sendEvent(ReactNativeFirebaseMessagingSerializer.remoteMessageToEvent(remoteMessage, true));
         }
+        ReactNativeFirebaseMessagingReceiver.notifications.remove(messageId);
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:233]: similar to above, you've changed the logical structure *and* the data types at the same time, which makes this difficult to untangle while reading it.

It appears that all you really *must* do is pop the RemoteMessageMap vs RemoteMessage ?

Can you do this chunk with the same effect but *only* altering the data types to be the Map you need?

**Review by mikehardy — CHANGES_REQUESTED** [review]
Interesting! I like this in general and it appears at the JS level this is non-breaking, it is just adding something that should be there, so that's fantastic as it means I can merge it and release it quickly

As commented in the specific code spots I really really wish that the change had been minimal, it appears the diff is much larger than it needs to be as the conditionals were restructured

Also even though it's at the java level some people use this library in brownfield apps and since the Store was a public interface we need to preserve the meaning of the old symbols as this is not something worth doing a breaking change over (but if they're marked 'deprecated' at least we can purge them in the next breaking change round)

I'm about to do an 11.3 release with a large-ish batch of other items and I can release this after once it's shaped up, that will also have the side-effect - since you are interested in using it immediately - of making the patch-set vs "current release" much smaller since it will only have this change once "current release" is more current and you re-push this to generate a new patch set

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java (hunk 2 above)
Comment (mcorner) [reply packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java]: fixed

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java (hunk 3 above)
Comment (mcorner) [reply packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java]: fixed

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java (hunk 4 above)
Comment (mcorner) [reply packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java]: It isn't *quite* that simple since we are still dealing with maps and remote messages, but your point is taken on the minimal changes.  Take a look, I think I cleaned it up nicely.

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java (hunk 5 above)
Comment (mcorner) [reply packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java]: Same here, I made the most minimal changes I could think of.

**Review by mikehardy — APPROVED** [review]
Nice! That is a squeaky clean diff - I was pretty sure it was correct before hand just on visual inspection - notwithstanding the actual test results posted - but now it's obvious, and I really appreciate the backwards-compatibility on the Java symbols

I should be able to get this out as a 11.3.1 shortly but in the meantime since 11.3.0 did just go out, the patch set should be empty except this change, making the patch-package usage a lot less anxiety-inducing

Thanks!
