### PR TITLE
fix(messaging, getToken): add options for messaging instance

### LINKED ISSUE #6173: 🔥 [🐛] `messaging().getToken()` no longer supports `messageSenderId`, breaks notifications
## Issue
When Firebase updated to use `getInstance()` instead of InstanceId to get a FCM token, this project dropped support for passing `messagingSenderId` into `getToken()`. This meant that apps which initialized the project using options in `initializeApp` would inadvertently get a token for the default project rather than the expected project.  Base on the current implementation in this library, I don't see a similar workaround as worked before for passing `messagingSenderId`.  
In trying to verify this issue, I stumbled upon: https://stackoverflow.com/questions/62253691/firebasemessaging-getinstancefirebaseapp-for-secondary-app-supposed-to-be-publ.  
I can report that after having locally changed `FirebaseMessaging.getInstance()` in `getToken()` in **ReactNativeFirebaseMessagingModule** to `FirebaseApp.getInstance(<project_name>).get(FirebaseMessaging.class)`, notifications again work on the expected project.  
Although this is tested on Android, I would _hope_ a similar fix is available for iOS (both platforms exhibit the issue).

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.7.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Cloud Messaging`
- **Are you using `TypeScript`?**
  - `N/A`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by ecexplorer**
### Description

Adds `projectId` and `senderId` token options to set messaging instance to use with FCM (see attached issue)

### Related issues

Fixes #6173

### Release Summary
Adds options for `getToken()` to use specific messaging instances. NOTE: BREAKING ARGUMENTS from prior v11 authorizedEntity/scope.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Because we're a monorepo you can't really target your package.json to use this, the way to use a PR that is in progress is via patch-package and the patch set generated from the workflow I set up - it will generate a fresh set of patches every time it runs, vs current head of `main`: https://github.com/invertase/react-native-firebase/actions/workflows/create_test_patches.yml - click in there on the most recent run for your PR and you should see a patches.zip you can download and integrate

**Review by mikehardy — COMMENTED** [review]
On a first scan, other than the trivial lint stuff, this looks really good, thanks for posting it up.
I am worried (not in a specific way, just in a way I am always worried...) about backwards compatibility, so I'll pull this myself and check it to, before merging. But I don't see anything wrong at the moment

**Review by mikehardy — CHANGES_REQUESTED** [review]
:thinking:  - really sorry for the long delay @ecexplorer - I just looked more closely at this as I was doing a batch of firebase work and I see that deleteToken (which is followed by a getToken) is now failing in a cross-platform way - both ios and android failing that e2e test for some reason. Is this code working in your environment?

**Comment by ecexplorer** [comment]
> 

@mikehardy No apologies necessary, I also got pulled away from this (still important, just had to knock out some other work). Good shout on the `deleteToken()` calls needing to mirror the same messaging instance/senderId. I can see the APIs needed there and will work later this week to push an update that should resolve those.

**Comment by ecexplorer** [comment]
@mikehardy If you have a chance, I could use some help on this PR.
- All the linting issues are resolved
- I added the needed args to `deleteToken` and did some overall cleanup around my work

The tests appear to still be failing? I don't understand the iOS error, it seems to complain about the native FCM call, but that's just lifted from https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessaging.h#L325.
On Android, the `deleteToken()` test is timing out.

**Comment by mikehardy** [comment]
Hey @ecexplorer  - I think the iOS was a typo, if you code this (or just open this) in Xcode you'll get code completion etc and it may help

Do you run this locally at all? It's surprising to get a compile error in CI and a timeout in CI if you are developing this locally and testing this locally, you should see them at that stage I think. The timeout in Android actually has the smell of a full Android app crash based on the logs, and I'm curious what you see when you take that deleteToken e2e test and alter if from `it` to `it.only` to focus on it and just run it by itself. My hunch is it is a red box error message

Our CI keep the adb logcat from execution https://github.com/invertase/react-native-firebase/actions/runs/2374482507 - it looks like

```

05-23 23:53:55.687 10876 11151 E unknown:ReactNative: Exception in native call
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: java.lang.IllegalStateException: FirebaseApp with name react-native-firebase-testing doesn't exist. Available app names: [DEFAULT], functionsAppTHbPf1, secondaryFromNative
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:219)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.getToken(ReactNativeFirebaseMessagingModule.java:125)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at androidx.test.espresso.base.LooperIdlingResourceInterrogationHandler$2.run(LooperIdlingResourceInterrogationHandler.java:3)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:223)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
05-23 23:53:55.687 10876 11151 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:923)
```

So perhaps the default options this PR is populating when TokenOptions are not specified are not correct?

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java [hunk 1]
```diff
@@ -120,8 +121,9 @@ public void setAutoInitEnabled(Boolean enabled, Promise promise) {
   }
 
   @ReactMethod
-  public void getToken(Promise promise) {
-    Tasks.call(getExecutor(), () -> Tasks.await(FirebaseMessaging.getInstance().getToken()))
+  public void getToken(String projectId, String senderId, Promise promise) {
+    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(projectId).get(FirebaseMessaging.class);
```
Comment (FranciscoPDNeto) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:125]: I think actually the getInstance expects an app name, not the projectId. So probably it is better to change that variable name (https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/FirebaseApp#getInstance(java.lang.String))

File: packages/messaging/lib/index.js [hunk 2]
```diff
@@ -154,12 +155,34 @@ class FirebaseMessagingModule extends FirebaseModule {
...
+    if (!isUndefined(projectId) && !isString(projectId)) {
+      throw new Error("firebase.messaging().getToken(*) 'projectId' expected a string.");
+    }
+
+    if (!isUndefined(senderId) && !isString(senderId)) {
+      throw new Error("firebase.messaging().getToken(*) 'senderId' expected a string.");
+    }
+
+    return this.native.getToken(
+      projectId || this.app.options.projectId,
```
Comment (FranciscoPDNeto) [inline packages/messaging/lib/index.js:168]: So once it's not the projectId but the appName that the getInstance expects, you should pass this.app.name, I've tested locally here and it worked

File: packages/messaging/lib/index.js [hunk 3]
```diff
@@ -154,12 +155,34 @@ class FirebaseMessagingModule extends FirebaseModule {
...
+    if (!isUndefined(projectId) && !isString(projectId)) {
+      throw new Error("firebase.messaging().deleteToken(*) 'projectId' expected a string.");
+    }
+
+    if (!isUndefined(senderId) && !isString(senderId)) {
+      throw new Error("firebase.messaging().deleteToken(*) 'senderId' expected a string.");
+    }
+
+    return this.native.deleteToken(
+      projectId || this.app.options.projectId,
```
Comment (FranciscoPDNeto) [inline packages/messaging/lib/index.js:183]: So once it's not the projectId but the appName that the getInstance expects, you should pass this.app.name, I've tested locally here and it worked

File: packages/messaging/lib/index.js (hunk 2 above)
Comment (mikehardy) [reply packages/messaging/lib/index.js:168]: Great! Thanks for checking that, and I agree with you as the error message was clearly suggesting app names as the possible values that could be sent in. Might be close on this whole PR with that change to `appName` as a TokenOptions object property plus the typo fix in firebase-ios-sdk method name above

Comment (ecexplorer) [reply packages/messaging/lib/index.js]: @mikehardy @FranciscoPDNeto HUGE Thank You for the suggestions in here. I believe I've applied them all, and see the fixes reflected, BUT there seem to be more test errors that are even more elusive. Let me know if y'all understand the new issues?

Comment (FranciscoPDNeto) [reply packages/messaging/lib/index.js]: Yes, this test that failed on iOS is failing here at my local, I saw that @mikehardy put an if to skip this into CI, but it seems that is running anyway (Here it was the only test that failed)

Comment (FranciscoPDNeto) [reply packages/messaging/lib/index.js]: I was thinking that maybe this failing can be related to the latest updates on main branch, because yesterday when I tried it was not failing (using the fork that was kind of 30 commits behind the main). On iOS it was failing another test, but not that one, and the android tests were passing

Comment (mikehardy) [reply packages/messaging/lib/index.js]: I've got a commit locally that fixes the iOS storage reference thing - it's not related to this PR at all, one of the helper functions I wrote to install storage security rules was async and (classic!) I forgot the await, so it's in a race with usage of the rules and sometime it works (android, sometimes iOS), sometimes it fails (ios sometimes). I'll commit that in a moment. It appears the test suite made it past the auth token part of the test already so this PR is likely good to go, reviewing now

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java [hunk 4]
```diff
@@ -133,11 +135,12 @@ public void getToken(Promise promise) {
   }
 
   @ReactMethod
-  public void deleteToken(Promise promise) {
+  public void deleteToken(String projectId, String senderId, Promise promise) {
+    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(projectId).get(FirebaseMessaging.class);
```
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:139]:
```suggestion
  public void deleteToken(String appName, String senderId, Promise promise) {
    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(appName).get(FirebaseMessaging.class);
```

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java (hunk 1 above)
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:125]:
```suggestion
  public void getToken(String appName, String senderId, Promise promise) {
    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(appName).get(FirebaseMessaging.class);
```

**Review by mikehardy — APPROVED** [review]
just making the native method parameters match the javascript names now that we know it's app name instead of project name. That's a non-functional change (assuming I did not have a typo or something).

CI failures are unrelated. I'll approve this then assuming CI either goes green or fail *after* the auth tests that exercise token delete, this will be good to merge + release

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java (hunk 1 above)
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:125]:
```suggestion
  public void getToken(String appName, String senderId, Promise promise) {
    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(appName).get(FirebaseMessaging.class);
```

Comment (mikehardy) [reply packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:125]: Interesting, I think after I approve it I can no longer do the "make comment with suggestion" / "commit using github UI" thing. No worries, will pull local and patch up, only takes a moment

**Review by mikehardy — CHANGES_REQUESTED** [review]
Mmm - I'm not able to push to your repo but I successfully run tests when rebased against #6270 locally so this is good to go *assuming* native method param names change from projectId to appName - if you make that change I'll merge+release :rocket: 

(it's possible perhaps that once I unapprove I can make suggesting and commit them, so I may try that but can't predict the github UI, it's inscrutable sometimes)

File: packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java (hunk 1 above)
Comment (mikehardy) [inline packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java:125]:
```suggestion
  public void getToken(String appName, String senderId, Promise promise) {
    FirebaseMessaging messagingInstance = FirebaseApp.getInstance(appName).get(FirebaseMessaging.class);
```

File: packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m [hunk 5]
```diff
@@ -107,7 +107,11 @@ - (NSDictionary *)constantsToExport {
   }
 }
 
-RCT_EXPORT_METHOD(getToken : (RCTPromiseResolveBlock)resolve : (RCTPromiseRejectBlock)reject) {
+RCT_EXPORT_METHOD(getToken
+                  : (NSString *)projectId
```
Comment (mikehardy) [inline packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m:111]:
```suggestion
                  : (NSString *)appName
```

File: packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m [hunk 6]
```diff
@@ -123,23 +127,30 @@ - (NSDictionary *)constantsToExport {
...
-RCT_EXPORT_METHOD(deleteToken : (RCTPromiseResolveBlock)resolve : (RCTPromiseRejectBlock)reject) {
-  [[FIRMessaging messaging] deleteTokenWithCompletion:^(NSError *_Nullable error) {
-    if (error) {
-      [RNFBSharedUtils rejectPromiseWithNSError:reject error:error];
-    } else {
-      resolve([NSNull null]);
-    }
-  }];
+RCT_EXPORT_METHOD(deleteToken
+                  : (NSString *)projectId
```
Comment (mikehardy) [inline packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m:141]:
```suggestion
                  : (NSString *)appName
```

**Review by mikehardy — CHANGES_REQUESTED** [review]

**Comment by ecexplorer** [comment]
> Mmm - I'm not able to push to your repo but I successfully run tests when rebased against #6270 locally so this is good to go _assuming_ native method param names change from projectId to appName - if you make that change I'll merge+release 🚀
> 
> (it's possible perhaps that once I unapprove I can make suggesting and commit them, so I may try that but can't predict the github UI, it's inscrutable sometimes)

Done! Sorry I missed that, and thanks for the work on this!!

**Review by mikehardy — APPROVED** [review]
A thing of beauty!
