### PR TITLE
fix(app-check, types): Correct ReactNativeFirebaseAppCheckProvider options type

### LINKED ISSUE #6886: AppCheck follow up issues
This is an umbrella issue to collect known problems with the recent AppCheck overhaul released as v17 here from PR #6847 

- [x] iOS debugToken not applied from config - still requires environment variable setup
- [x] Android debugToken style [changed internally in firebase-android-sdk 31.2.0](https://github.com/firebase/firebase-android-sdk/pull/4436/commits/c339aa03dd2ff9f0105d32d06c214f1b922605e9) and needs re-work here before we can bump the firebase-android-sdk to current 
- [x] how to use debug provider is confusing in the docs - need to clarify perhaps with a debug/release build switch example
- [x] argument validation in config block could be improved
- [x] missing index.d.ts definition for `newReactNativeFirebaseAppCheckProvider` method (which exists in index.js...)
- [ ] no modular API

### PR DESCRIPTION
**Pull request by frw**
### Description

After the recent update to AppCheck types in 17.2.0, there is still an issue with configuring ReactNativeFirebaseAppCheckProvider when attempting to follow https://rnfirebase.io/app-check/usage:

image

The issue is due to a mismatch in the TypeScript declaration file.

`ReactNativeFirebaseAppCheckProvider` takes in a single options object:

https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/lib/ReactNativeFirebaseAppCheckProvider.js#L6

while the type declaration indicates it takes in 4 separate objects for each platform:

https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/lib/index.d.ts#L139-L142

### Related issues

Fixes #6886 

### Release Summary

- Update ReactNativeFirebaseAppCheckProvider options type

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

- Tried using the new types and ensured they worked as expected

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
🤦 really sorry for the error in the first place, thanks a bunch for the PR fixup, this looks correct

File: packages/app-check/lib/index.d.ts [hunk 1]
```diff
@@ -135,12 +135,12 @@ export namespace FirebaseAppCheckTypes {
      * so AppCheck has the same experience across all platforms, with the only difference being the native
      * providers you choose to use on each platform.
      */
-    configure(
+    configure(options: {
       web?: ReactNativeFirebaseAppCheckProviderWebOptions,
       android?: ReactNativeFirebaseAppCheckProviderAndroidOptions,
       apple?: ReactNativeFirebaseAppCheckProviderAppleOptions,
       isTokenAutoRefreshEnabled?: boolean,
```
Comment (mikehardy) [inline packages/app-check/lib/index.d.ts:142]:
```suggestion
      web?: ReactNativeFirebaseAppCheckProviderWebOptions;
      android?: ReactNativeFirebaseAppCheckProviderAndroidOptions;
      apple?: ReactNativeFirebaseAppCheckProviderAppleOptions;
      isTokenAutoRefreshEnabled?: boolean;
```
