### PR TITLE
fix(auth, iOS): Expo plugin: skip expo-router for auth URLs

### LINKED ISSUE #7258: [🐛🔥] @react-native-firebase/auth (phone auth) + Expo Router - Redirected to appScheme://firebaseuth/link after resolving recaptcha in ios simulator
## Issue

Describe your issue here

I'm currently developing a phone authentication for my ios app using @react-native-firebase/auth specifically `Phone Auth`

in ios simulator we don't have access to `Silent APNs notifications` for app verification and we will need to resolve recaptcha instead
ref:
image

The integration went smoothly, but when I tried to resolve the reCAPTCHA on the simulator, I got redirected to appScheme://firebaseuth/link. I believe it's a deep link to that route.

Since I use [expo-router](https://docs.expo.dev/routing/introduction/), it automatically detects that link and redirected to that screen as shown in this video

https://github.com/invertase/react-native-firebase/assets/46083126/d974cb90-2dce-4d0a-b97e-c6e0f06ae46c

### Expected Result

It should stay with the current screen after resolving the captcha

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "",
  "version": "1.0.0",
  "main": "expo-router/entry",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "lint": "echo \"Running eslint check\" && eslint --fix .",
    "tsc": "tsc"
  },
  "dependencies": {
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/auth": "^18.3.0",
    "expo": "~49.0.3",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.6",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-splash-screen": "~0.20.4",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "eslint": "^8.45.0",
    "eslint-config-universe": "^11.3.0",
    "eslint-plugin-prettier": "5.0.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^3.0.0",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 103.33 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/bryan/.gem/ruby/2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/bryan/.rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/auth": "^18.3.0",
- **`Firebase` module(s) you're using that has the issue:**
  - firebase phone auth
- **Are you using `TypeScript`?**
  - Yes

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by jey**
### Description

*Summary*:
Fix [#7258: @react-native-firebase/auth (phone auth) + Expo Router - Redirected to appScheme://firebaseuth/link after resolving recaptcha in ios simulator](https://github.com/invertase/react-native-firebase/issues/7258)

*Problem*:
When using `@react-native-firebase/auth` and `expo-router` in the same application, the phone number login method on iOS fails in some scenarios. In particular, when Firebase uses its ReCAPTCHA verifier (e.g. when running in the iOS simulator), the application ends up navigating away from the login page to a new route `/firebaseauth/link`. 

*Cause*:
After the user has completed the captcha challenge, the WebView redirects back to the application using an iOS deep link of the form `${googleServiceJson.REVERSED_CLIENT_ID}://firebaseauth/link?${queryParams}`. This inadvertently gets handled by Expo Router, which treats it as a navigation event to a route called `/firebaseauth/link`.

The root cause of this is a bad interaction between a feature in the Firebase iOS SDK and one in Expo Router:
- Firebase uses a technique called "swizzling" to automatically intercept the `openURL` call and do its business, but then it also passes along the same `openURL` call to our application so we can handle it too.
- Our iOS app's `AppDelegate` is supposed to return `TRUE` if it can handle the provided URL, and `FALSE` if it can't.
- When using Expo Router, our AppDelegate is configured to just pass the URL along onto the router.
- However, Expo Router always answers "yes I can handle this URL" -- even if it's going to "handle" it by displaying a "Not Found" error.

This interacts badly because it's effectively like Expo Router is hijacking the call that's intended for Firebase Auth. Yet, this situation only occurs because Firebase Auth is forwarding the `openURL` call to our app even after it has already handled it.

*Solution*:
This PR automatically updates the AppDelegate's `openURL` method to not handle URLs for the hostname `"firebaseauth"`, under the assumption that it's already being handled by Firebase.

- Adds a configuration option to `@react-native-firebase/auth` Expo plugin called `captchaOpenUrlFix`.
- When `captchaOpenUrlFix` option is unset or `"default"`, automatically applies patch if `expo-router` plugin is detected in Expo config.
- Robust error handling and reporting

*TODO*:
- Documentation updates

CC: @mikehardy 
### Related issues
Fixes #7258, #7953 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [X] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [X] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

Comprehensive unit tests have been added:
- plugin configurations
- positive and negative examples of patching
- tests for each error handling condition

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Oh wow - you are quick with this one!

As mentioned in the related issue, it's a bit delicate because it has to do regex-matching so it will likely break across some future version, but also, I'm not aware of any other way to do this

Given the fragility I think it has to be default-off and have a parameter that turns on this logic (named anything reasonable, like maybe "expoRouterCompatibilityPatch" ... or something)

If it had that, then most people could use the plugin perfectly safely and never break, and those that needed this would be the only ones affected

But in general: thanks so much for posting up a PR to help folks, we rely on community submissions for Expo stuff so it's a huge help here

**Comment by jey** [comment]
@mikehardy This is now ready for review, but I'm going to leave it marked as "Draft" because I'd like to also add some documentation updates.

I made the plugin configurable as you suggested [here](https://github.com/invertase/react-native-firebase/issues/7258#issuecomment-2562879144), but I also made it so that in the default configuration, it will automatically apply the patch only if "expo-router" is also detected (by looking in the Expo Plugins list). I think this is a happy medium because it addresses the edge cases of projects where it's not applicable, but also makes it easy for the median Expo user. My impression is that the typical Expo user is not comfortable dealing with native code, and having more manual configuration changes to apply and figure out on top of the already complex configuration required for RNFirebase Phone Auth to work.

**Comment by jey** [comment]
CC:  @Brandon-Perry

File: packages/auth/plugin/src/ios/openUrlFix.ts [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+export function shouldApplyIosOpenUrlFix({
+  config,
+  props,
+}: {
+  config: ExpoConfig;
+  props?: PluginConfigType;
+}): boolean {
+  const flag = props?.ios?.captchaOpenUrlFix;
+  if (flag === undefined || flag === 'default') {
+    // by default, apply the fix whenever 'expo-router' is detected in the same project
```
Comment (mikehardy) [inline packages/auth/plugin/src/ios/openUrlFix.ts:45]: I think this is a good choice, default Just Works, but people *can* disable it if they need to for whatever reason

File: packages/auth/plugin/src/ios/openUrlFix.ts [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+        throw new Error("Failed to apply iOS openURL fix because no 'openURL' method was found");
+      } else {
+        WarningAggregator.addWarningIOS(
+          '@react-native-firebase/auth',
+          "Skipping iOS openURL fix because no 'openURL' method was found",
+        );
+        return config;
+      }
+    } else {
+      return {
```
Comment (mikehardy) [inline packages/auth/plugin/src/ios/openUrlFix.ts:77]: I don't know what the typical Expo plugin user experience is like, so this may be something no one wants.
However, if we're modifying the AppDelegate for expo-router users by default, would people be interested in seeing the equivalent of an "info" printout (definitely not warning, just info) that says something like `@react-native-firebase/auth Expo config plugin modified iOS AppDelegate openURL method to ignore firebaseauth reCAPTCHA redirect URLs."

My thought is it could be juuussst enough of a breadcrumb for people to search the plugin for the message and learn what's going on if they have problems with it ever.

Or it might be something no expo plugin does, for reasons (perhaps "quiet" is encouraged and noise is strongly discouraged?).

Any answer is fine, "implementor's choice" meaning ignore this idea or do something about it at your full option as you'll have more experience here than me either way

**Review by mikehardy — APPROVED** [review]
This looks amazing, and amazingly robust.
Would be nice to have some docs though I'm not sure *exactly* where they'd go - perhaps there is an expo section in the auth module already, if so there would work

Left one note you can handle however you see fit about perhaps emitting an info message on successful execution

Default approve at this point, pending whatever you'd like to consider it done, but all okay by me

Cheers!

File: packages/auth/plugin/src/ios/openUrlFix.ts (hunk 2 above)
Comment (jey) [reply packages/auth/plugin/src/ios/openUrlFix.ts:84]: Sounds good, I've added that warning when the "default" configuration is in use

**Review by mikehardy — APPROVED** [review]
awesome

**Comment by mikehardy** [comment]
The patch-package failure is not related to this PR and is non-blocking here. It was a scheduled deprecation of `npx react-native init` that I was aware of from other usages but I forgot it was used here so I haven't forward-ported yet.

File: packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts [hunk 3]
```diff
@@ -199,6 +199,31 @@ describe('Config Plugin iOS Tests - openUrlFix', () => {
...
+          path: fixturePath,
+          language: 'objc',
+          contents: appDelegate,
+        } as AppDelegateProjectFile,
+        modRawConfig: { name: 'TestName', slug: 'TestSlug' },
+      };
+      const props = undefined;
+      const spy = jest
+        .spyOn(WarningAggregator, 'addWarningIOS')
+        .mockImplementation(() => undefined);
```
Comment (jey) [inline packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts:220]: @mikehardy btw for some reason this call to `mockImplementation` is *required* so we don't get get spurious error messages, yet the one at [Line 249](https://github.com/invertase/react-native-firebase/pull/8203/commits/7f0412e4a450696603bd1a2eac3957c21188c3c6#diff-0f4c13658fa7495aea4ea28afee8291a8e3c4ee58922219759045179709e67d1R249) is not required. In particular here's the output when I remove both calls to `mockImplementation`:
```
 PASS  packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts
  ● Console

    console.warn
      » ios: @react-native-firebase/auth: modifying iOS AppDelegate openURL method to ignore firebaseauth reCAPTCHA redirect URLs

      77 |     } else {
      78 |       if (configValue === 'default') {
    > 79 |         WarningAggregator.addWarningIOS(
         |                           ^
      80 |           '@react-native-firebase/auth',
      81 |           'modifying iOS AppDelegate openURL method to ignore firebaseauth reCAPTCHA redirect URLs',
      82 |         );

      at Object.warn (packages/auth/node_modules/@expo/config-plugins/src/utils/warnings.ts:32:11)
      at withOpenUrlFixForAppDelegate (packages/auth/plugin/src/ios/openUrlFix.ts:79:27)
      at packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts:221:35
      at step (packages/auth/node_modules/tslib/tslib.js:195:27)
      at Object.next (packages/auth/node_modules/tslib/tslib.js:176:57)
      at fulfilled (packages/auth/node_modules/tslib/tslib.js:166:62)

 PASS  packages/auth/plugin/__tests__/iosPlugin_urlTypes.test.ts

Test Suites: 2 passed, 2 total
Tests:       26 passed, 26 total
Snapshots:   6 passed, 6 total
Time:        2.235 s
Ran all test suites matching /packages\/auth\/plugin\/__tests__\//i.
```

File: packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts [hunk 4]
```diff
@@ -219,7 +244,9 @@ describe('Config Plugin iOS Tests - openUrlFix', () => {
         modRawConfig: { name: 'TestName', slug: 'TestSlug' },
       };
       const props = undefined;
-      const spy = jest.spyOn(WarningAggregator, 'addWarningIOS');
+      const spy = jest
+        .spyOn(WarningAggregator, 'addWarningIOS')
+        .mockImplementation(() => undefined);
```
Comment (jey) [inline packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts:249]: @mikehardy related to [Line 220](https://github.com/invertase/react-native-firebase/pull/8203/commits/7f0412e4a450696603bd1a2eac3957c21188c3c6#diff-0f4c13658fa7495aea4ea28afee8291a8e3c4ee58922219759045179709e67d1R220), when commenting this line `mockImplementation()` , why doesn't jest print a warning message with something like:
```
» ios: @react-native-firebase/auth: Skipping iOS openURL fix because no 'openURL' method was found
```

**Comment by jey** [comment]
@mikehardy thanks for accepting and merging this PR! I left a comment or two just now about a lingering mystery that came up when writing the tests

File: packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts (hunk 3 above)
Comment (mikehardy) [reply packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts:220]: If you don't mock it, it will print the warning as requested in code, so seeing the warning if you remove the mock *seems* to me to make sense here, and then...

I wonder if the second one is behaving seemingly-strangely is because the spy is one thing but the mocked implementation is separate - such that the mental model is 2 attempts to spy but only one object that is mocked or not, and if you mock it once it stays mocked. Test of hypothesis would be to reset mocks after test ? Then following my hypothesis the second test should behave as expected if mocked or not (silent if mocked, producing the warn output if not mocked)
