### PR TITLE
Fix authStateChanged after app is reloaded (fixes #1677)

### LINKED ISSUE #1677: onAuthStateChanged not returning any result on iOS Sumulator
## Issue

I just updated to rnfirebase 5.1.0 from 5.0 and noticed that `onAuthStateChanged` works in a strange way on ios simulator. I need to reload app twice for the method to return a result. The first time I reload the app the callback is never invoked! Then after reloading again it works as expecred. If I reload again it does not work and it repeats.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```
pod 'Firebase/Core', '~> 5.11.0'
pod 'Firebase/Auth', '~> 5.11.0'
pod 'Firebase/Firestore', '~> 5.11.0'
pod 'Firebase/Functions', '~> 5.11.0'
pod 'Firebase/Storage', '~> 5.11.0'
pod 'Firebase/Messaging', '~> 5.11.0'
pod 'Firebase/DynamicLinks', '~> 5.11.0'
```

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `iOS 12`
- **Operating System:**
  - [x] MacOS, version: `10.14`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `Xcode 10`
- **`React Native` version:**
  - `0.57.4`
- **`React Native Firebase` library version:**
  - `5.1`
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [x] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] Invites
  - [ ] Instance ID
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by ghsdh3409**
### Summary

- It closes #1677.
- `onAuthStateChanged` sometimes is not fired after app is reloaded on iOS.
  - I checked it on `v5.1.0`.
- I found followings on debugging.
  - When the app is reloaded, `dealloc` sometimes is not called. So, deallocation task does not work.
  - iOS native callback addAuthStateDidChangeListener works well.  
  - `emitter.bridge` is null when JS `onAuthStateChanged` is not fired.
- I added deallocation task using `RCTInvalidating`.
  - ref: https://stackoverflow.com/a/38161889

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan
- How to reproduce
  - https://github.com/invertase/react-native-firebase/issues/1677#issuecomment-440154916

### Release Plan

[IOS][BUGFIX] [FirebaseModule] - Fix authStateChanged is not called after app is reloaded 

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

File: ios/RNFirebase/auth/RNFirebaseAuth.m [hunk 1]
```diff
@@ -62,6 +62,22 @@ - (void)dealloc {
   }
 }
 
+- (void)invalidate {
+  // dealloc sometimes is not called when app is reloaded.
```
Comment (ghsdh3409) [inline ios/RNFirebase/auth/RNFirebaseAuth.m]: The logic below is exactly the same as `dealloc`.

**Comment by Ehesp** [comment]
@ghsdh3409 Thanks very much for this. Could you approve the CLA?

**Comment by ghsdh3409** [comment]
@Ehesp 
Thanks for letting me know! I approved!

**Comment by Salakar** [comment]
@ghsdh3409 thanks for debugging and fixing this 🎉
